#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Generates src/ma_fm_tables.inc, the integer lookup tables used by the
# fixed-point FM core (ma_fm_fixed.cpp). The core itself never touches libm.
import math
import sys

def arr(name, ctype, vals, per_line=12):
    lines = [f"static const {ctype} {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(str(v) for v in vals[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)

def q15(x):
    return int(round(x * 32767.0))

N = 1024
sin_t = [q15(math.sin(2 * math.pi * i / N)) for i in range(N)]
sqr_t = [q15(math.tanh(3.0 * math.sin(2 * math.pi * i / N))) for i in range(N)]
saw_t = []
for i in range(N):
    x = i / N
    v = (math.sin(2 * math.pi * x) + 0.5 * math.sin(2 * math.pi * 2 * x)
         + 0.333 * math.sin(2 * math.pi * 3 * x)) * 0.6
    saw_t.append(q15(v))

# 2^(i/64) for i = 0..64, Q16
pow2 = [int(round(65536 * 2 ** (i / 64.0))) for i in range(65)]

# total level: 0.75 dB per step, 1.0 == 32768
tl = [int(round(32768 * 10 ** (-0.75 * t / 20.0))) for t in range(63)] + [0]

# envelope times in microseconds for rates 1..15 (index 0 unused)
def times(fast, slow):
    out = [0]
    for r in range(1, 16):
        t = slow * (fast / slow) ** ((r - 1) / 14.0)
        out.append(int(round(t * 1e6)))
    return out
atk_us = times(0.0008, 0.35)
dec_us = times(0.004, 4.0)

# key-scale level: dB per octave / 6.0206 dB per halving, Q16
ksl = [int(round(65536 * d / 6.020599913)) for d in (0.0, 1.5, 3.0, 6.0)]

out = ["// SPDX-License-Identifier: Apache-2.0",
       "// Generated by tools/gen_fm_tables.py. Do not edit by hand.",
       arr("kSin", "int16_t", sin_t),
       arr("kSqr", "int16_t", sqr_t),
       arr("kSaw", "int16_t", saw_t),
       arr("kPow2Frac", "uint32_t", pow2, 8),
       arr("kTlGain", "uint16_t", tl, 16),
       arr("kAtkUs", "uint32_t", atk_us, 8),
       arr("kDecUs", "uint32_t", dec_us, 8),
       arr("kKslExpQ16", "uint32_t", ksl, 4),
       ""]
path = sys.argv[1] if len(sys.argv) > 1 else "src/ma_fm_tables.inc"
with open(path, "w") as f:
    f.write("\n".join(out))
print("wrote", path)
